### ISSUE TITLE
还不够现用啊，缺少阿里这些dns吧

### ISSUE THREAD

**Issue by aogg** [easy-docker/smartdns#1]
而且感觉
https://cloudflare-dns.com/dns-query
和
1.1.1.1是重复了吧

**Comment by aogg** [comment]
而且应该将日志输出到
/proc/self/fd/1
/proc/self/fd/2
中才好

**Comment by ghostry** [comment]
> 而且应该将日志输出到
> /proc/self/fd/1
> /proc/self/fd/2
> 中才好

日志不知道怎么整，你了解吗

**Comment by morrisjazz** [comment]
請問有沒有圖形介面啊
這個看著都蒙了呀

**Comment by ghostry** [comment]
> 請問有沒有圖形介面啊 這個看著都蒙了呀

配置方面可以去[原项目](https://github.com/pymumu/smartdns )看看，这个项目的目的就是让用户不用关心配置。
